rules:
  default:
    protection:
      required_status_checks:
        contexts:
          - continuous-integration/circle-ci
      required_pull_request_reviews:
        required_approving_review_count: 2